# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 06d9add381adf94372d780365b3025c9c4cf7467fc76dbea3f9fa2ee3d2d3f1a237bafa1b209dc8c54aa08f52d9d8553d3504f3572e85c5962183c9db9598828

test:
  secret_key_base: c0fe271fdca36265e1a24a224e28b54d8211af7020053778e760e50a9e593aa79db766384b14c0cd6096a467f1c1c7d47bfa38b1025e550134c6025b42f9fbc6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
